
esel , none
esel , a    , elem ,  , 938
esel , a    , elem ,  , 939
esel , a    , elem ,  , 940
esel , a    , elem ,  , 941
esel , a    , elem ,  , 942
esel , a    , elem ,  , 943
esel , a    , elem ,  , 944
esel , a    , elem ,  , 945
esel , a    , elem ,  , 973
esel , a    , elem ,  , 974
esel , a    , elem ,  , 975
esel , a    , elem ,  , 976
esel , a    , elem ,  , 977
esel , a    , elem ,  , 978
esel , a    , elem ,  , 979
esel , a    , elem ,  , 980
esel , a    , elem ,  , 1371
esel , a    , elem ,  , 1372
esel , a    , elem ,  , 1385
esel , a    , elem ,  , 1386
esel , a    , elem ,  , 1399
esel , a    , elem ,  , 1400
esel , a    , elem ,  , 1413
esel , a    , elem ,  , 1414
esel , a    , elem ,  , 1427
esel , a    , elem ,  , 1428
esel , a    , elem ,  , 1441
esel , a    , elem ,  , 1442
esel , a    , elem ,  , 1455
esel , a    , elem ,  , 1456
esel , a    , elem ,  , 1469
esel , a    , elem ,  , 1470
esel , a    , elem ,  , 1498
esel , a    , elem ,  , 1499
esel , a    , elem ,  , 1500
esel , a    , elem ,  , 1501
esel , a    , elem ,  , 1502
esel , a    , elem ,  , 1503
esel , a    , elem ,  , 1504
esel , a    , elem ,  , 1505
esel , a    , elem ,  , 1533
esel , a    , elem ,  , 1534
esel , a    , elem ,  , 1535
esel , a    , elem ,  , 1536
esel , a    , elem ,  , 1537
esel , a    , elem ,  , 1538
esel , a    , elem ,  , 1539
esel , a    , elem ,  , 1540
esel , a    , elem ,  , 1568
esel , a    , elem ,  , 1569
esel , a    , elem ,  , 1570
esel , a    , elem ,  , 1571
esel , a    , elem ,  , 1572
esel , a    , elem ,  , 1573
esel , a    , elem ,  , 1574
esel , a    , elem ,  , 1575
esel , a    , elem ,  , 1603
esel , a    , elem ,  , 1604
esel , a    , elem ,  , 1605
esel , a    , elem ,  , 1606
esel , a    , elem ,  , 1607
esel , a    , elem ,  , 1608
esel , a    , elem ,  , 1609
esel , a    , elem ,  , 1610
esel , a    , elem ,  , 1638
esel , a    , elem ,  , 1639
esel , a    , elem ,  , 1640
esel , a    , elem ,  , 1641
esel , a    , elem ,  , 1642
esel , a    , elem ,  , 1643
esel , a    , elem ,  , 1644
esel , a    , elem ,  , 1645
esel , a    , elem ,  , 1673
esel , a    , elem ,  , 1674
esel , a    , elem ,  , 1675
esel , a    , elem ,  , 1676
esel , a    , elem ,  , 1677
esel , a    , elem ,  , 1678
esel , a    , elem ,  , 1679
esel , a    , elem ,  , 1680
esel , a    , elem ,  , 1708
esel , a    , elem ,  , 1709
esel , a    , elem ,  , 1710
esel , a    , elem ,  , 1711
esel , a    , elem ,  , 1712
esel , a    , elem ,  , 1713
esel , a    , elem ,  , 1714
esel , a    , elem ,  , 1715
esel , a    , elem ,  , 1743
esel , a    , elem ,  , 1744
esel , a    , elem ,  , 1745
esel , a    , elem ,  , 1746
esel , a    , elem ,  , 1747
esel , a    , elem ,  , 1748
esel , a    , elem ,  , 1749
esel , a    , elem ,  , 1750
esel , a    , elem ,  , 1778
esel , a    , elem ,  , 1779
esel , a    , elem ,  , 1780
esel , a    , elem ,  , 1781
esel , a    , elem ,  , 1782
esel , a    , elem ,  , 1783
esel , a    , elem ,  , 1784
esel , a    , elem ,  , 1785
esel , a    , elem ,  , 1813
esel , a    , elem ,  , 1814
esel , a    , elem ,  , 1815
esel , a    , elem ,  , 1816
esel , a    , elem ,  , 1817
esel , a    , elem ,  , 1818
esel , a    , elem ,  , 1819
esel , a    , elem ,  , 1820
esel , a    , elem ,  , 1848
esel , a    , elem ,  , 1849
esel , a    , elem ,  , 1850
esel , a    , elem ,  , 1851
esel , a    , elem ,  , 1852
esel , a    , elem ,  , 1853
esel , a    , elem ,  , 1854
esel , a    , elem ,  , 1855
esel , a    , elem ,  , 1883
esel , a    , elem ,  , 1884
esel , a    , elem ,  , 1885
esel , a    , elem ,  , 1886
esel , a    , elem ,  , 1887
esel , a    , elem ,  , 1888
esel , a    , elem ,  , 1889
esel , a    , elem ,  , 1890
esel , a    , elem ,  , 1918
esel , a    , elem ,  , 1919
esel , a    , elem ,  , 1920
esel , a    , elem ,  , 1921
esel , a    , elem ,  , 1922
esel , a    , elem ,  , 1923
esel , a    , elem ,  , 1924
esel , a    , elem ,  , 1925
esel , a    , elem ,  , 1953
esel , a    , elem ,  , 1954
esel , a    , elem ,  , 1955
esel , a    , elem ,  , 1956
esel , a    , elem ,  , 1957
esel , a    , elem ,  , 1958
esel , a    , elem ,  , 1959
esel , a    , elem ,  , 1960
esel , a    , elem ,  , 4635
esel , a    , elem ,  , 4636
esel , a    , elem ,  , 4637
esel , a    , elem ,  , 4638
esel , a    , elem ,  , 4639
esel , a    , elem ,  , 4640
esel , a    , elem ,  , 4641
esel , a    , elem ,  , 4671
esel , a    , elem ,  , 4672
esel , a    , elem ,  , 4673
esel , a    , elem ,  , 4674
esel , a    , elem ,  , 4704
esel , a    , elem ,  , 4705
esel , a    , elem ,  , 4706
esel , a    , elem ,  , 4707
esel , a    , elem ,  , 4708
esel , a    , elem ,  , 4709
esel , a    , elem ,  , 4713
esel , a    , elem ,  , 4714
esel , a    , elem ,  , 4715
esel , a    , elem ,  , 4716
esel , a    , elem ,  , 4774
esel , a    , elem ,  , 4775
esel , a    , elem ,  , 4776
esel , a    , elem ,  , 4777
esel , a    , elem ,  , 4778
esel , a    , elem ,  , 4779
esel , a    , elem ,  , 4780
esel , a    , elem ,  , 4781
esel , a    , elem ,  , 4782
esel , a    , elem ,  , 4783
esel , a    , elem ,  , 4784
esel , a    , elem ,  , 4785
esel , a    , elem ,  , 4786
esel , a    , elem ,  , 4787
esel , a    , elem ,  , 4788
esel , a    , elem ,  , 4789
esel , a    , elem ,  , 4790
esel , a    , elem ,  , 4791
esel , a    , elem ,  , 4792
esel , a    , elem ,  , 4793
esel , a    , elem ,  , 4794
esel , a    , elem ,  , 4795
esel , a    , elem ,  , 4796
esel , a    , elem ,  , 4797
esel , a    , elem ,  , 4798
esel , a    , elem ,  , 4799
esel , a    , elem ,  , 4800
esel , a    , elem ,  , 4801
esel , a    , elem ,  , 4802
esel , a    , elem ,  , 4803
esel , a    , elem ,  , 4804
esel , a    , elem ,  , 4805
esel , a    , elem ,  , 4806
esel , a    , elem ,  , 4807
esel , a    , elem ,  , 4808
esel , a    , elem ,  , 4809
esel , a    , elem ,  , 4810
esel , a    , elem ,  , 4811
esel , a    , elem ,  , 4812
esel , a    , elem ,  , 4813
esel , a    , elem ,  , 4814
esel , a    , elem ,  , 4815
esel , a    , elem ,  , 4837
esel , a    , elem ,  , 4838
esel , a    , elem ,  , 4839
esel , a    , elem ,  , 4840
esel , a    , elem ,  , 4841
esel , a    , elem ,  , 4842
esel , a    , elem ,  , 4843
esel , a    , elem ,  , 4844
esel , a    , elem ,  , 4845
esel , a    , elem ,  , 4846
esel , a    , elem ,  , 4847
esel , a    , elem ,  , 4848
esel , a    , elem ,  , 4878
esel , a    , elem ,  , 4879
esel , a    , elem ,  , 4880
esel , a    , elem ,  , 4884
esel , a    , elem ,  , 4885
esel , a    , elem ,  , 4886
esel , a    , elem ,  , 4888
esel , a    , elem ,  , 4889
esel , a    , elem ,  , 6991
esel , a    , elem ,  , 6992
esel , a    , elem ,  , 7000
esel , a    , elem ,  , 7001
esel , a    , elem ,  , 7002
esel , a    , elem ,  , 7083
esel , a    , elem ,  , 7084
esel , a    , elem ,  , 7085
esel , a    , elem ,  , 7086
esel , a    , elem ,  , 7087
esel , a    , elem ,  , 7088
esel , a    , elem ,  , 7155
esel , a    , elem ,  , 7156
esel , a    , elem ,  , 7157
esel , a    , elem ,  , 7158
esel , a    , elem ,  , 7159
esel , a    , elem ,  , 7160
esel , a    , elem ,  , 7161
esel , a    , elem ,  , 7162
esel , a    , elem ,  , 7182
esel , a    , elem ,  , 7580
esel , a    , elem ,  , 7581
esel , a    , elem ,  , 7602
esel , a    , elem ,  , 7603
esel , a    , elem ,  , 7604
esel , a    , elem ,  , 7605
esel , a    , elem ,  , 7606
esel , a    , elem ,  , 7607
esel , a    , elem ,  , 7608
esel , a    , elem ,  , 7638
esel , a    , elem ,  , 7657
esel , a    , elem ,  , 7658
esel , a    , elem ,  , 7659
esel , a    , elem ,  , 7660
esel , a    , elem ,  , 7661
esel , a    , elem ,  , 7662
esel , a    , elem ,  , 7663
esel , a    , elem ,  , 7664
esel , a    , elem ,  , 7665
esel , a    , elem ,  , 7666
esel , a    , elem ,  , 7667
esel , a    , elem ,  , 7668
esel , a    , elem ,  , 7669
esel , a    , elem ,  , 7705
esel , a    , elem ,  , 7706

nsle,s

/auto,1
/view,1,1,1,1
lplot
/user,1
asel,all
lsla
asel,none
ksel,none
gplot
takepic,'ekill'

modmsh,detach
edele,all
esln,s,1
edele,all
esln,s
esel,r,ename,,180
nsle
edele,all
ndele,all
allsel

/eof

/input,'D:\Tools\Code\shell-box-tunnel\_ekill',mac
