! TUNNEL_V2_POSTDFLENVELOPE , lsNum
! TUNNEL_V2_POSTDFLENVELOPE , ARG1


_lsNum = ARG1

*do,nthModule,1,GEO_TUN_modules,1
  *if,nthModule,eq,1,then
    floorLeftBeg = KP_FLOOR_leftBeg
    floorLeftEnd = KP_FLOOR_leftEnd
    roofLeftBeg  = KP_ROOF_leftBeg
    roofLeftEnd  = KP_ROOF_leftEnd
  *else
    mthModule    = nthModule-1
    floorLeftBeg = KP_IWALL%mthModule%_botBeg
    floorLeftEnd = KP_IWALL%mthModule%_botEnd
    roofLeftBeg  = KP_IWALL%mthModule%_topBeg
    roofLeftEnd  = KP_IWALL%mthModule%_topEnd
  *endif

  *if,nthModule,eq,GEO_TUN_modules,then
    floorRightBeg = KP_FLOOR_rightBeg
    floorRightEnd = KP_FLOOR_rightEnd
    roofRightBeg  = KP_ROOF_rightBeg
    roofRightEnd  = KP_ROOF_rightEnd
  *else
    floorRightBeg = KP_IWALL%nthModule%_botBeg
    floorRightEnd = KP_IWALL%nthModule%_botEnd
    roofRightBeg  = KP_IWALL%nthModule%_topBeg
    roofRightEnd  = KP_IWALL%nthModule%_topEnd
  *endif

  cmsel,s,COMPA_floor
  esla
  nsle
  TUNNEL_V2_SPANDFLENV , floorLeftBeg , floorLeftEnd , floorRightBeg , floorRightEnd , 'FLOOR%nthModule%' , 'UY_frq_i' , 'DENV_floor' , _lsNum

  cmsel,s,COMPA_roof
  esla
  nsle
  TUNNEL_V2_SPANDFLENV , roofLeftBeg  , roofLeftEnd  , roofRightBeg  , roofRightEnd  , 'ROOF%nthModule%'  , 'UY_frq_i' , 'DENV_roof'  , _lsNum
*enddo

cmsel,s,COMPA_leftWall
esla
nsle
TUNNEL_V2_SPANDFLENV , KP_LWALL_botBeg    , KP_LWALL_botEnd    , KP_LWALL_topBeg   , KP_LWALL_topEnd   , 'LWALL'  , 'UX_frq_i' , 'DENV_lwall' , _lsNum
cmsel,s,COMPA_rightWall
esla
nsle
TUNNEL_V2_SPANDFLENV , KP_RWALL_botBeg    , KP_RWALL_botEnd    , KP_RWALL_topBeg   , KP_RWALL_topEnd   , 'RWALL'  , 'UX_frq_i' , 'DENV_rwall' , _lsNum

*if,GEO_APR_status,eq,1,then
  cmsel,s,COMPA_approachL
  esla
  nsle
  TUNNEL_V2_SPANDFLENV , KP_APPL_outBeg     , KP_APPL_outEnd     , KP_APPL_innBeg    , KP_APPL_innEnd    , 'APPL'   , 'UY_frq_i' , 'DENV_appl'  , _lsNum
  cmsel,s,COMPA_approachR
  esla
  nsle
  TUNNEL_V2_SPANDFLENV , KP_APPR_outBeg     , KP_APPR_outEnd     , KP_APPR_innBeg    , KP_APPR_innEnd    , 'APPR'   , 'UY_frq_i' , 'DENV_appr'  , _lsNum
*endif

*if,GEO_HDW1_status,eq,1,and,GEO_HDW1_type,eq,0,then
  ! TODO  account for inlet type 2 (unconnected approach slab)
  cmsel,s,COMPA_HDW1_slab
  cmsel,a,COMPA_HDW1_leftStiffener
  cmsel,a,COMPA_HDW1_rightStiffener
  esla
  nsle
  TUNNEL_V2_SPANDFLENV , KP_IN1SLB_rightBeg , KP_IN1SLB_rightEnd , KP_IN1SLB_leftBeg , KP_IN1SLB_leftEnd , 'IN1SLB' , 'UY_frq_i' , 'DENV_in1s'  , _lsNum
*endif
*if,GEO_HDW2_status,eq,1,and,GEO_HDW2_type,eq,0,then
  cmsel,s,COMPA_HDW2_slab
  cmsel,a,COMPA_HDW2_leftStiffener
  cmsel,a,COMPA_HDW2_rightStiffener
  esla
  nsle
  TUNNEL_V2_SPANDFLENV , KP_IN2SLB_rightBeg , KP_IN2SLB_rightEnd , KP_IN2SLB_leftBeg , KP_IN2SLB_leftEnd , 'IN2SLB' , 'UY_frq_i' , 'DENV_in2s'  , _lsNum
*endif
