! TUNNEL_V2_SMENDCAP , hdwNumber , tunnelCS , endCS
! TUNNEL_V2_SMENDCAP , ARG1      , ARG2     , ARG3


! Prepare environment
csbackup

! Get anchor positions in tunnel CS
csys,ARG3

cmsel,s,COMPA_floor
lsla
ksll
ksel,r,loc,z,0
ksel,r,loc,y,0
*get,xMax,kp,,mxloc,x
kBotLeft  = kp(0    , 0 , 0)
kBotRight = kp(xMax , 0 , 0)

cmsel,s,COMPA_roof
lsla
ksll
ksel,r,loc,z,0
*get,yMax,kp,,mxloc,y
kTopLeft  = kp(0    , yMax , 0)
kTopRight = kp(xMax , yMax , 0)

csys,ARG2

xBotLeft  = kx(kBotLeft)
yBotLeft  = ky(kBotLeft)
zBotLeft  = kz(kBotLeft)
xBotRight = kx(kBotRight)
yBotRight = ky(kBotRight)
zBotRight = kz(kBotRight)

xTopLeft  = kx(kTopLeft)
yTopLeft  = ky(kTopLeft)
zTopLeft  = kz(kTopLeft)
xTopRight = kx(kTopRight)
yTopRight = ky(kTopRight)
zTopRight = kz(kTopRight)

! Draw lid
zManual = 2

nextkp,'KP_lid',4

k , KP_lid(1) , xBotLeft  , yBotLeft  , zManual ! zBotLeft
k , KP_lid(2) , xBotRight , yBotRight , zManual ! zBotRight
k , KP_lid(3) , xTopRight , yTopRight , zManual ! zTopRight
k , KP_lid(4) , xTopLeft  , yTopLeft  , zManual ! zTopLeft

asel,none
lsel,none
a , KP_lid(1) , KP_lid(2) , KP_lid(3) , KP_lid(4)

! Export selection components
cm,COMPA_endcap%ARG1%,area
cm,COMPL_endcap%ARG1%,line

cmsel,s,COMPL_endcap%ARG1%
lsel,r,loc,y,yBotLeft
cm,COMPL_ENDCAP_bottom,line

cmsel,s,COMPL_endcap%ARG1%
lsel,r,loc,y,yTopLeft
cm,COMPL_ENDCAP_top,line

cmsel,s,COMPL_endcap%ARG1%
lsel,r,loc,x,xBotLeft
cm,COMPL_ENDCAP_right,line

cmsel,s,COMPL_endcap%ARG1%
lsel,r,loc,x,xBotRight
cm,COMPL_ENDCAP_left,line

! Clean up
csrestore
*del,KP_lid,,nopr
