! TUNNEL_V2_POST

/post1

set,last

! Applied loads
TUNNEL_V2_POSTLOADS

! Element tables
TUNNEL_V2_ETAB

! Envelopes
! TUNNEL_V2_POSTENVELOPES

! Vertical pressure transmitted to foundation soil
TUNNEL_V2_POSTSOIL

! Plot results
TUNNEL_V2_POSTSHELLS
/eof
TUNNEL_V2_POSTFRAMEPICS
TUNNEL_V2_POSTIWALLPICS
TUNNEL_V2_POSTFBEAMPICS

*if,GEO_ROOF_gapStrutCount,gt,0,then
  TUNNEL_V2_POSTSTRUTPICS
*endif

TUNNEL_V2_POSTINLETPICS

/eof
! Write results
TUNNEL_V2_WRRES

! Escrever resultados
TUNNEL_V2_MEMO

! Write report
TUNNEL_V2_REPORT !! TODO: format this

*if,GEO_HDW_status,eq,1,and,GEO_HDW_type,eq,0,then
  TUNNEL_V2_HDWRES
*endif

*if,GEO_APR_status,eq,1,then
  TUNNEL_V2_APPSLBRES
*endif
