! TUNNEL_V2_POSTSTRUTPICS


picRes    = 1500
baseScale = 20

*del , roof_struts ,      , nopr
*del , label_MB    ,      , nopr
*del , label_N     ,      , nopr
*del , label_V     ,      , nopr
*del , label_D     ,      , nopr
*dim , roof_struts , char , GEO_ROOF_gapStrutCount*2
*dim , label_MB    , char , GEO_ROOF_gapStrutCount*2
*dim , label_N     , char , GEO_ROOF_gapStrutCount*2
*dim , label_V     , char , GEO_ROOF_gapStrutCount*2
*dim , label_D     , char , GEO_ROOF_gapStrutCount*2

*do,nthStrut,1,GEO_ROOF_gapStrutCount,1
  roof_struts(2*nthStrut-1) = 'STRUT%nthStrut%'
  roof_struts(2*nthStrut-0) = 'STRUT%nthStrut%'

  label_MB(2*nthStrut-1) = 'MB_MIN'  , 'MB_MAX'
  label_N(2*nthStrut-1)  = 'N_MIN'   , 'N_MAX'
  label_V(2*nthStrut-1)  = 'V_MIN'   , 'V_MAX'
  label_D(2*nthStrut-1)  = 'DYB_MIN' , 'DYB_MAX'
*enddo

parm_roof_struts = 'roof_struts'
parm_label_MB    = 'label_MB'
parm_label_MP    = 'label_MP'
parm_label_V     = 'label_V'
parm_label_N     = 'label_N'
parm_label_D     = 'label_D'

paths_parm = 'parm_roof_struts'
mb_parm    = 'parm_label_MB'
mp_parm    = 'parm_label_MP'
v_parm     = 'parm_label_V'
n_parm     = 'parm_label_N'
d_parm     = 'parm_label_D'

view4w
windefa
wincln
clims
boldfont,1
g_picres,picRes

view1w
wintitle,1,'COBERTURA - ESTRONCAS',' ','ELU-Normal',,1,13

view2w ,   ,  , 1 ,   , 1 , 3
view2w , 1 ,  , 1 , 1 , 1 , 2
view2w , 1 ,  , 3 , 1 , 3 , 4

wintitle , 1 , ' ' , 'MOMENTO FLETOR' , '[kNm]' ,  , 1 , 13
wintitle , 2 , ' ' , 'FOR. CORTANTE'  , '[kN]'  ,  , 1 , 13
wintitle , 3 , ' ' , 'FOR. NORMAL'    , '[kN]'  ,  , 1 , 13
wintitle , 4 , ' ' , 'FLECHA'         , '[mm]'  ,  , 1 , 13

allsel
/gline,all,0
/color,defa
/type,all,3
/pnum,defa
/number,0
/udoc,1,cntr,bottom
/udoc,2,cntr,bottom
/udoc,3,cntr,bottom
/udoc,4,cntr,bottom
/plopts,leg3,on
/eshape,0
/gformat,f,2,1

wpcsys,1,CS_tunnel
wpcsys,2,CS_tunnel
wpcsys,3,CS_tunnel
wpcsys,4,CS_tunnel

cmsel,s,COMPA_tunnel
esla
cm,COMPE_bg,elem
/color,cm,dgra,COMPE_bg

/auto,all
cmsel,s,COMPA_tunnel
esla
nsle
/eshape,1
eplot
/user,all

go2png,picRes
  /device,vector,on
  eplot
  /noerase
  /device,vector,off

  cmsel,s,COMPA_struts
  esla
  nsle
  eplot

  /window,1,on
  /window,2,off
  /window,3,off
  /window,4,off
  cleanplot ,'mpathplot' , baseScale , , 'paths_parm' , 'mb_parm'

  /window,1,off
  /window,2,on
  /window,3,off
  /window,4,off
  cleanplot ,'mpathplot' , baseScale , , 'paths_parm' , 'v_parm'

  /window,1,off
  /window,2,off
  /window,3,on
  /window,4,off
  cleanplot , 'mpathplot' , baseScale , , 'paths_parm' , 'n_parm'

  /window,1,off
  /window,2,off
  /window,3,off
  /window,4,on
  /gformat,f,2,2
  cleanplot, 'mpathplot' , baseScale , , 'paths_parm' , 'd_parm'

endpng,'RES_struts',,,,,FOLDER_results
/erase
/annot,dele
/eshape,0

view1w
windefa,1
