! TUNNEL_V2_POSTDFL
! TUNNEL_V2_POSTDFL


! KP_FLOOR_leftBeg / KP_FLOOR_rightBeg
! KP_FLOOR_leftEnd / KP_FLOOR_rightEnd
!
! KP_ROOF_leftBeg / KP_ROOF_rightBeg
! KP_ROOF_leftEnd / KP_ROOF_rightEnd
!
! KP_LWALL_topBeg / KP_LWALL_topEnd
! KP_LWALL_botBeg / KP_LWALL_botEnd
!
! KP_RWALL_topBeg / KP_RWALL_topEnd
! KP_RWALL_botBeg / KP_RWALL_botEnd
!
! KP_APPL_outBeg / KP_APPL_outEnd
! KP_APPL_innBeg / KP_APPL_innEnd
!
! KP_APPR_outBeg / KP_APPR_outEnd
! KP_APPR_innBeg / KP_APPR_innEnd
!
! KP_IN1SLB_rightBeg / KP_IN1SLB_rightEnd
! KP_IN1SLB_leftBeg  / KP_IN1SLB_leftEnd
!
! KP_IN2SLB_rightBeg / KP_IN2SLB_rightEnd
! KP_IN2SLB_leftBeg  / KP_IN2SLB_leftEnd


POST_slabDeflectionPathLabel = 'DFL'

! Initialize deflection envelope arrays
*del , DENV_roof  ,      , nopr
*del , DENV_floor ,      , nopr
*del , DENV_lwall ,      , nopr
*del , DENV_rwall ,      , nopr
*del , DENV_appl  ,      , nopr
*del , DENV_appr  ,      , nopr
*del , DENV_in1s  ,      , nopr
*del , DENV_in2s  ,      , nopr
*dim , DENV_roof  , char , 2    , 1
*dim , DENV_floor , char , 2    , 1
*dim , DENV_lwall , char , 2    , 1
*dim , DENV_rwall , char , 2    , 1
*dim , DENV_appl  , char , 2    , 1
*dim , DENV_appr  , char , 2    , 1
*dim , DENV_in1s  , char , 2    , 1
*dim , DENV_in2s  , char , 2    , 1

*do,nthModule,1,GEO_TUN_modules,1
  DENV_roof(1,nthModule)  = 'ROOF%nthModule%'
  DENV_roof(2,nthModule)  = POST_slabDeflectionPathLabel
  DENV_floor(1,nthModule) = 'FLOOR%nthModule%'
  DENV_floor(2,nthModule) = POST_slabDeflectionPathLabel
*enddo

DENV_lwall(1,1) = 'LWALL'
DENV_lwall(2,1) = POST_slabDeflectionPathLabel
DENV_rwall(1,1) = 'RWALL'
DENV_rwall(2,1) = POST_slabDeflectionPathLabel
DENV_appl(1,1)  = 'APS1'
DENV_appl(2,1)  = POST_slabDeflectionPathLabel
DENV_appr(1,1)  = 'APS2'
DENV_appr(2,1)  = POST_slabDeflectionPathLabel
DENV_in1s(1,1)  = 'INS1'
DENV_in1s(2,1)  = POST_slabDeflectionPathLabel
DENV_in2s(1,1)  = 'INS2'
DENV_in2s(2,1)  = POST_slabDeflectionPathLabel

pthenv,'CLEAR',DENV_floor
pthenv,'CLEAR',DENV_roof
pthenv,'CLEAR',DENV_lwall
pthenv,'CLEAR',DENV_rwall
pthenv,'CLEAR',DENV_appl
pthenv,'CLEAR',DENV_appr
pthenv,'CLEAR',DENV_in1s
pthenv,'CLEAR',DENV_in2s

*do,nthLS,1,LoadStepCount,1

  *do,nthModule,1,GEO_TUN_modules,1
    *if,nthModule,eq,1,then
      floorLeftBeg = KP_FLOOR_leftBeg
      floorLeftEnd = KP_FLOOR_leftEnd
      roofLeftBeg  = KP_ROOF_leftBeg
      roofLeftEnd  = KP_ROOF_leftEnd
    *else
      mthModule    = nthModule-1
      floorLeftBeg = KP_IWALL%mthModule%_botBeg
      floorLeftEnd = KP_IWALL%mthModule%_botEnd
      roofLeftBeg  = KP_IWALL%mthModule%_topBeg
      roofLeftEnd  = KP_IWALL%mthModule%_topEnd
    *endif

    *if,nthModule,eq,GEO_TUN_modules,then
      floorRightBeg = KP_FLOOR_rightBeg
      floorRightEnd = KP_FLOOR_rightEnd
      roofRightBeg  = KP_ROOF_rightBeg
      roofRightEnd  = KP_ROOF_rightEnd
    *else
      floorRightBeg = KP_IWALL%nthModule%_botBeg
      floorRightEnd = KP_IWALL%nthModule%_botEnd
      roofRightBeg  = KP_IWALL%nthModule%_topBeg
      roofRightEnd  = KP_IWALL%nthModule%_topEnd
    *endif

    TUNNEL_V2_SPANDFLENV , floorLeftBeg , floorLeftEnd , floorRightBeg , floorRightEnd , 'FLOOR%nthModule%' , 'UY_frq' , DENV_floor , nthLS
    TUNNEL_V2_SPANDFLENV , roofLeftBeg  , roofLeftEnd  , roofRightBeg  , roofRightEnd  , 'ROOF%nthModule%'  , 'UY_frq' , DENV_roof  , nthLS

  *enddo

  TUNNEL_V2_SPANDFLENV , KP_LWALL_botBeg    , KP_LWALL_botEnd    , KP_LWALL_topBeg   , KP_LWALL_topEnd   , 'LWALL'  , 'UX_frq' , DENV_lwall , nthLS
  TUNNEL_V2_SPANDFLENV , KP_RWALL_botBeg    , KP_RWALL_botEnd    , KP_RWALL_topBeg   , KP_RWALL_topEnd   , 'RWALL'  , 'UX_frq' , DENV_rwall , nthLS

  TUNNEL_V2_SPANDFLENV , KP_APPL_outBeg     , KP_APPL_outEnd     , KP_APPL_innBeg    , KP_APPL_outEnd    , 'APPL'   , 'UY_frq' , DENV_appl  , nthLS
  TUNNEL_V2_SPANDFLENV , KP_APPR_outBeg     , KP_APPR_outEnd     , KP_APPR_innBeg    , KP_APPR_outEnd    , 'APPR'   , 'UY_frq' , DENV_appr  , nthLS

  TUNNEL_V2_SPANDFLENV , KP_IN1SLB_rightBeg , KP_IN1SLB_rightEnd , KP_IN1SLB_leftBeg , KP_IN1SLB_leftEnd , 'IN1SLB' , 'UY_frq' , DENV_in1s  , nthLS
  TUNNEL_V2_SPANDFLENV , KP_IN2SLB_rightBeg , KP_IN2SLB_rightEnd , KP_IN2SLB_leftBeg , KP_IN2SLB_leftEnd , 'IN2SLB' , 'UY_frq' , DENV_in2s  , nthLS

*enddo
