! TUNNEL_V2_FEMENDCAPS


*if,GEO_ENDCAP1_status,eq,0,and,GEO_ENDCAP2_status,eq,0,then
  *return,-1
*endif

! Set attributes
TUNNEL_V2_FEMAATT , 'COMPA_endcap1' , CS_begSkewed , SEC_endcap1
TUNNEL_V2_FEMAATT , 'COMPA_endcap2' , CS_endSkewed , SEC_endcap2

! Mesh solid model
cmsel,s,COMPA_endcaps
aesize,all,FEM_HDW_esize
amesh,all

! Adjust nodal directions
csys,CS_begSkewed
cmsel,s,COMPA_endcap1
nsla,s,1
nrotat,all

csys,CS_endSkewed
cmsel,s,COMPA_endcap2
nsla,s,1
nrotat,all

! Connect parts
*if,GEO_ENDCAP1_status,eq,1,then
  l2acnt , 'COMPA_endcap1' , 'COMPL_tunnelBeg' ,  , GEO_ENDCAP1_connection
*endif

*if,GEO_ENDCAP2_status,eq,1,then
  ! l2acnt , 'COMPA_endcap2' , 'COMPL_tunnelEnd' ,  , GEO_ENDCAP2_connection
  l2acnt , 'COMPA_roof'      , 'COMPL_ENDCAP_top'    ,  , 1
  l2acnt , 'COMPA_floor'     , 'COMPL_ENDCAP_bottom' ,  , 1
  l2acnt , 'COMPA_leftWall'  , 'COMPL_ENDCAP_left'   ,  , 1
  l2acnt , 'COMPA_rightWall' , 'COMPL_ENDCAP_right'  ,  , 1
*endif
