! TUNNEL_V2_SPANDFLENV , kpLeftBeg , kpLeftEnd , kpRightBeg , kpRightEnd , pthName , etName , envTable , lstep
! TUNNEL_V2_SPANDFLENV , ARG1      , ARG2      , ARG3       , ARG4       , ARG5    , ARG6   , ARG7     , ARG8


_pthName  = upcase(ARG5)
_etName   = upcase(ARG6)
_envTable = ARG7
_lstep    = ARG8

pathCount = 20
pathDivs  = 20
dflLabel  = POST_slabDeflectionPathLabel

csbackup
csys,0

xiLeft  = kx(ARG1)
yiLeft  = ky(ARG1)
ziLeft  = kz(ARG1)

xjLeft  = kx(ARG2)
yjLeft  = ky(ARG2)
zjLeft  = kz(ARG2)

xiRight = kx(ARG3)
yiRight = ky(ARG3)
ziRight = kz(ARG3)

xjRight = kx(ARG4)
yjRight = ky(ARG4)
zjRight = kz(ARG4)

xStepLeft  = (xjLeft - xiLeft)/(pathCount-1)
yStepLeft  = (yjLeft - yiLeft)/(pathCount-1)
zStepLeft  = (zjLeft - ziLeft)/(pathCount-1)
xStepRight = (xjRight - xiRight)/(pathCount-1)
yStepRight = (yjRight - yiRight)/(pathCount-1)
zStepRight = (zjRight - ziRight)/(pathCount-1)

*del , left_x  ,  , nopr
*del , left_y  ,  , nopr
*del , left_z  ,  , nopr
*del , right_x ,  , nopr
*del , right_y ,  , nopr
*del , right_z ,  , nopr
*dim , left_x  ,  , pathCount
*dim , left_y  ,  , pathCount
*dim , left_z  ,  , pathCount
*dim , right_x ,  , pathCount
*dim , right_y ,  , pathCount
*dim , right_z ,  , pathCount

*vfill , left_x  , ramp , xiLeft  , xStepLeft
*vfill , left_y  , ramp , yiLeft  , yStepLeft
*vfill , left_z  , ramp , ziLeft  , zStepLeft
*vfill , right_x , ramp , xiRight , xStepRight
*vfill , right_y , ramp , yiRight , yStepRight
*vfill , right_z , ramp , ziRight , zStepRight

*do,nthPath,1,pathCount,1
  xi = left_x(nthPath)
  yi = left_y(nthPath)
  zi = left_z(nthPath)
  xj = right_x(nthPath)
  yj = right_y(nthPath)
  zj = right_z(nthPath)

  padele,%_pthName%
  path,_pthName,2,,pathDivs
  ppath,1,,xi,yi,zi
  ppath,2,,xj,yj,zj

  pdef,'U',etab,%_etName%
  pthrebase,'U',0,dflLabel

  pthenv,'UPDATE',_envTable,_lstep
*enddo

csrestore
