! TUNNEL_V2_POSTS2BEAM , cmaName , pthName , envelope_table
! TUNNEL_V2_POSTS2BEAM , ARG1    , ARG2    , ARG3


_cmaName      = ARG1
_pthName      = ARG2
_envelopeName = ARG3
pathDivs      = 20

! Prepare environment
csbackup
abackup
ebackup
nbackup

! Collect attributes from representative element (based on current area selection)
cmsel,s,%_cmaName%
esla
nsle
n1 = ndnext(0)
e1 = elnext(0)
*del , esysNum ,      , nopr
*get , esysNum , elem , e1     , attr , esys
*get , secNum  , elem , e1     , attr , secn
*get , width   , shel , secNum , prop , tthk

! Get path-defining nodes
csys,esysNum
wpcsys,-1
nwpave,n1
cswpla,CS_dummy,cart
ndbbox,'xmin','xmax','ymin','ymax'

tn1 = node(xmin , ymax , 0)
tn2 = node(xmax , ymax , 0)
bn1 = node(xmin , ymin , 0)
bn2 = node(xmax , ymin , 0)

! Calculate beam cross-sectional properties
depth   = ymax-ymin
area    = depth*width
modulus = width*(depth**2)/6

! Generate virtual beam results
pth2beam,tn1,tn2,bn1,bn2,_pthName,1,pathDivs,modulus,area,,_envelopeName

! Calculate internal reaction variations
path  , _pthName
pcalc , add      , 'MP_DLT' , 'MP_MAX' , 'MP_MIN' , 1 , -1
pcalc , add      , 'MB_DLT' , 'MB_MAX' , 'MB_MIN' , 1 , -1
pcalc , add      , 'V_DLT'  , 'V_MAX'  , 'V_MIN'  , 1 , -1

! Clean up
csrestore
arestore
elrestore
nrestore
