! TUNNEL_V2_ENDCAPDEADLOAD


*do,nthCap,1,2,1

  *if,GEO_ENDCAP%nthCap%_status,ne,1,cycle

  cmsel,s,COMPA_endcap%nthCap%
  nsla,s,1
  *get,nc,node,,count

  *del , endcap_nodes  ,  , nopr
  *del , endcap_forces ,  , nopr
  *dim , endcap_nodes  ,  , nc
  *dim , endcap_forces ,  , nc

  ndnum = 0
  *do,nthNode,1,nc,1

    ndnum  = ndnext(ndnum)
    xNode  = nx(ndnum)
    yNode  = ny(ndnum)
    zNode  = nz(ndnum)
    ndArea = arnode(ndnum)

    ! Calculate embankment height above node
    tunnel_v2_yabove, 'yAbove', zNode

    nthWaterY              = ((WaterY<yAbove)>yNode)
    EffectiveSoilPressure  = LOAD_SOIL_gammat_d*(yAbove-nthWaterY)+LOAD_SOIL_gammasub_d*(nthWaterY-yNode)
    HorEffectivePressure   = EffectiveSoilPressure*RestEPCoefficient-2*MAT_SOIL_cohesion*sqrt(RestEPCoefficient)
    HorEffectivePressure   = (HorEffectivePressure>0)
    WaterPressure          = (nthWaterY-yNode)*LOAD_WATER_gammaw_d
    DeadNodalLoad          = apportionedArea*(HorEffectivePressure+WaterPressure)
    endcap_nodes(nthNode)  = ndnum
    endcap_forces(nthNode) = DeadNodalLoad

  *enddo

  ! Apply loads
  f , endcap_nodes(1:nc) , fz , endcap_forces(1:nc)

*enddo
