! TUNNEL_V2_OBLQSECT

CMSEL,S,COMPA_Roof
NSLA,S,1

NDLeft_i=NODE(0,Eff_GalleryHeight,zSect_b)
NDLeft_j=NODE(0,Eff_GalleryHeight,zSect_e)

NSEL,R,LOC,X,Eff_GalleryWidth
NDRight_i=NODE(Eff_GalleryWidth,Eff_GalleryHeight,zSect_bR)

*if,NDLeft_i,EQ,NDLeftBeginning,THEN
    NDplane=NDRightEnd
*else
    NDplane=NDLeftBeginning
*endif

ALLSEL

*get,CSMax,CDSY,,NUM,MAX
CS_tmp=CSMax+1
CS,CS_tmp,CART,NDLeft_i,NDRight_i,NDplane
CSYS,CS_tmp

NSEL,S,LOC,Y,NY(NDLeft_i),NY(NDLeft_j)
CSYS,CS_Tunnel


