! TUNNEL_V1_APPSLBRES

!!
!! aprox
!!
cmsel,s,compa_approach
esla,s
nsle,s

pletab,emn_my,1
cntrlims,,,'APPSLB_M'
plnsol,u,y
cntrlims,,,'APPSLB_U'



*cfopen,'RES_APPSLB',txt
    *vwrite,FILE_name
Identification: %c

    *vwrite
    (' ')

    *vwrite
    ('Units: kN, kNm, mm')

    *vwrite
    (' ')

    *vwrite,APPSLB_M/1000
    ('ASlb M:', F12.2)
    *vwrite,APPSLB_U*1e3
    ('ASlb U:', F12.5)
*cfclos



