! TUNNEL_V1_YABOVE, parm,   NZ
! TUNNEL_V1_YABOVE, arg1, arg2

! Calculate embankment height above node
*if,GEO_EMB_slopeBeg,eq,90,then
    yBeg=yPT2
*else
    *afun,DEG
    yBeg=yPT1+TAN(GEO_EMB_slopeBeg)*(arg2-zPT1)
    *afun,RAD
*endif
*if,GEO_EMB_slopeEnd,eq,90,then
    yEnd=yPT2
*else
    *afun,DEG
    yEnd=yPT4+TAN(GEO_EMB_slopeEnd)*(zPT4-arg2)
    *afun,RAD
*endif
yPlateau=yPT2

%arg1%=(0>(yBeg<(yPlateau<yEnd)))
