! TUNNEL_V2_OBLQSECT


cmsel,S,COMPA_Roof
nsla,S,1

NDLeft_i = NODE(0,Eff_GalleryHeight,zSect_b)
NDLeft_j = NODE(0,Eff_GalleryHeight,zSect_e)

nsel,R,LOC,X,Eff_GalleryWidth
NDRight_i = NODE(Eff_GalleryWidth,Eff_GalleryHeight,zSect_bR)

*if,NDLeft_i,EQ,NDLeftBeginning,THEN
  NDplane = NDRightEnd
*else
  NDplane = NDLeftBeginning
*endif

allsel

*get,CSMax,CDSY,,NUM,MAX
CS_tmp = CSMax+1
cs,CS_tmp,CART,NDLeft_i,NDRight_i,NDplane
csys,CS_tmp

nsel,S,LOC,Y,NY(NDLeft_i),NY(NDLeft_j)
csys,CS_Tunnel
