! TUNNEL_V2_POSTDFLPICS


! Capture images of deflection envelopes
baseScale = 10

*del , floor_paths ,      , nopr
*del , roof_paths  ,      , nopr
*del , lwall_paths ,      , nopr
*del , rwall_paths ,      , nopr
*del , dfl_labels  ,      , nopr
*dim , floor_paths , char , 2*GEO_TUN_modules
*dim , roof_paths  , char , 2*GEO_TUN_modules
*dim , dfl_labels  , char , 2*GEO_TUN_modules
*dim , lwall_paths , char , 2
*dim , rwall_paths , char , 2

*do,nthModule,1,GEO_TUN_modules,1
  floor_paths(2*nthModule-1) = DENV_floor(1,nthModule) , DENV_floor(1,nthModule)
  roof_paths(2*nthModule-1)  = DENV_roof(1,nthModule) , DENV_roof(1,nthModule)
  dfl_labels(2*nthModule-1)  = '%POST_slabDeflectionPathLabel%+' , '%POST_slabDeflectionPathLabel%-'
*enddo

lwall_paths(1) = 'LWALL','LWALL'
rwall_paths(1) = 'RWALL','RWALL'

_lwall_paths = 'lwall_paths' $ __lwall_paths = '_lwall_paths'
_rwall_paths = 'rwall_paths' $ __rwall_paths = '_rwall_paths'
_floor_paths = 'floor_paths' $ __floor_paths = '_floor_paths'
_roof_paths  = 'roof_paths'  $ __roof_paths  = '_roof_paths'
_dfl_labels  = 'dfl_labels'  $ __dfl_labels  = '_dfl_labels'

view1w
wincln,1
g_picres,GRAPH_picRes
boldfont,1
wintitle,1,'PASSAGEM INFERIOR','FLECHA','ELS-Freq. [mm]',,1,13

/gformat,f,2,2
/plopts,leg3,on
/eshape,1
/angle,1,0
/type,1,3

cmsel,s,COMPA_tunnel
esla
nsle
cm,COMPE_bg,elem
/color,cm,dgra,COMPE_bg
wpcsys,1,CS_tunnel
/auto,1
eplot
/user,1

go2png,GRAPH_picRes
  eplot
  /noerase

  /udoc,1,cntr,top
  cleanplot,'mpathplot',baseScale,,'__roof_paths','__dfl_labels'

  /udoc,1,cntr,bottom
  cleanplot,'mpathplot',baseScale,,'__floor_paths','__dfl_labels'

  /udoc,1,cntr,left
  cleanplot,'mpathplot',baseScale,,'__lwall_paths','__dfl_labels'

  /udoc,1,cntr,right
  cleanplot,'mpathplot',baseScale,,'__rwall_paths','__dfl_labels'

  /device,vector,on
  /type,1,3
  /color,cm,whit,COMPE_bg
  eplot

endpng,'PI_deflections',,,,,FOLDER_results

/erase
/annot,dele
/type,1,3
/device,vector,off
/eshape,0
view1w
windefa,1
