! TUNNEL_V2_ETCVL


! Prepare environment
csbackup
csys,CS_tunnel

*msg,ui
ETABLE: performing convolutions...

! Initialize element tables
convolutionTableCount = 2
*del , convolution_etnames ,      , nopr
*dim , convolution_etnames , char , convolutionTableCount
! convolution_etnames(1)  = 'DW_MX'   , 'EMN_MX'  , 'EMX_MX'  , 'EAB_MX'
! convolution_etnames(5)  = 'DW_MY'   , 'EMN_MY'  , 'EMX_MY'  , 'EAB_MY'
convolution_etnames(1)  = 'DW_Q'    , 'EAB_Q'
! convolution_etnames(11) = 'EPOS_MX' , 'ENEG_MX' , 'EPOS_MY' , 'ENEG_MY'

*do,nthConv,1,convolutionTableCount,1
  lab = convolution_etnames(nthConv)
  sadd,'A%lab%','%lab%',,1
*enddo

! Apply convolution to tunnel shells
cmsel,s,COMPE_roof
nsle,s
etbcvl,POST_convolutionRadius,'convolution_etnames','XZ'

cmsel,s,COMPE_floor
nsle,s
etbcvl,POST_convolutionRadius,'convolution_etnames','XZ'

cmsel,s,COMPE_leftWall
nsle,s
etbcvl,POST_convolutionRadius,'convolution_etnames','YZ'

cmsel,s,COMPE_rightWall
nsle,s
etbcvl,POST_convolutionRadius,'convolution_etnames','YZ'

*if,GEO_IWALL_count,eq,0,then
  cmsel,s,COMPE_innerWalls
  nsle,s
  etbcvl,POST_convolutionRadius,'convolution_etnames','YZ'
*endif

! Apply convolution to headwall shells
*if,GEO_HDW_status,ge,1,then
  *do,nthInlet,1,2,1

    cmsel,s,COMPE_HDW_leftWall
    cmsel,r,COMPE_HDW_%nthInlet%
    nsle,s
    etbcvl,POST_convolutionRadius,'convolution_etnames','YZ'

    cmsel,s,COMPE_HDW_rightWall
    cmsel,r,COMPE_HDW_%nthInlet%
    nsle,s
    etbcvl,POST_convolutionRadius,'convolution_etnames','YZ'

    cmsel,s,COMPE_HDW_slab
    cmsel,r,COMPE_HDW_%nthInlet%
    nsle,s
    etbcvl,POST_convolutionRadius,'convolution_etnames','XZ'

    cmsel,s,COMPE_HDW_stiffener
    cmsel,r,COMPE_HDW_%nthInlet%
    nsle,s
    etbcvl,POST_convolutionRadius,'convolution_etnames','XZ'

    cmsel,s,COMPE_HDW_footing
    cmsel,r,COMPE_HDW_%nthInlet%
    nsle,s
    etbcvl,POST_convolutionRadius,'convolution_etnames','XZ'

  *enddo
*endif

! Clean up
csrestore
