! TUNNEL_V2_POSTDFLPICS


baseScale = 10
maxLabel  = '%POST_slabDeflectionPathLabel%+'
minLabel  = '%POST_slabDeflectionPathLabel%-'

! Tunnel deflections
*del , floor_paths ,      , nopr
*del , roof_paths  ,      , nopr
*del , lwall_paths ,      , nopr
*del , rwall_paths ,      , nopr
*del , dfl_labels  ,      , nopr
*dim , floor_paths , char , 2*GEO_TUN_modules
*dim , roof_paths  , char , 2*GEO_TUN_modules
*dim , dfl_labels  , char , 2*GEO_TUN_modules
*dim , lwall_paths , char , 2
*dim , rwall_paths , char , 2

*do,nthModule,1,GEO_TUN_modules,1
  floor_paths(2*nthModule-1) = DENV_floor(1,nthModule) , DENV_floor(1,nthModule)
  roof_paths(2*nthModule-1)  = DENV_roof(1,nthModule)  , DENV_roof(1,nthModule)
  dfl_labels(2*nthModule-1)  = maxLabel                , minLabel
*enddo

lwall_paths(1) = 'LWALL','LWALL'
rwall_paths(1) = 'RWALL','RWALL'

_lwall_paths = 'lwall_paths' $ __lwall_paths = '_lwall_paths'
_rwall_paths = 'rwall_paths' $ __rwall_paths = '_rwall_paths'
_floor_paths = 'floor_paths' $ __floor_paths = '_floor_paths'
_roof_paths  = 'roof_paths'  $ __roof_paths  = '_roof_paths'
_dfl_labels  = 'dfl_labels'  $ __dfl_labels  = '_dfl_labels'

view1w
wincln,1
g_picres,GRAPH_picRes
boldfont,1
wintitle,1,'PASSAGEM INFERIOR','FLECHA','ELS-Freq. [mm]',,1,13

/gformat,f,2,2
/plopts,leg3,on
/eshape,1
/angle,1,0
/type,1,3

cmsel,s,COMPA_tunnel
esla
nsle
cm,COMPE_bg,elem
/color,cm,dgra,COMPE_bg
wpcsys,1,CS_tunnel
/auto,1
eplot
/user,1

go2png,GRAPH_picRes
  eplot
  /noerase

  /udoc,1,cntr,top
  cleanplot,'mpathplot',baseScale,,'__roof_paths','__dfl_labels'

  /udoc,1,cntr,bottom
  cleanplot,'mpathplot',baseScale,,'__floor_paths','__dfl_labels'

  /udoc,1,cntr,left
  cleanplot,'mpathplot',baseScale,,'__lwall_paths','__dfl_labels'

  /udoc,1,cntr,right
  cleanplot,'mpathplot',baseScale,,'__rwall_paths','__dfl_labels'

  /device,vector,on
  /type,1,3
  /color,cm,whit,COMPE_bg
  eplot

endpng,'PI_deflections',,,,,FOLDER_results

/erase
/annot,dele
/type,1,3
/device,vector,off
/eshape,0
view1w
windefa,1

! Inlet slab deflections
*del , inlet1_paths ,      , nopr
*del , inlet2_paths ,      , nopr
*del , dfl_labels   ,      , nopr
*dim , inlet1_paths , char , 2
*dim , inlet2_paths , char , 2
*dim , dfl_labels   , char , 2

inlet1_paths(1) = 'IN1SLB' , 'IN1SLB'
inlet2_paths(1) = 'IN2SLB' , 'IN2SLB'
dfl_labels(1)   = maxLabel , minLabel

_inlet1_paths = 'inlet1_paths' $ __inlet1_paths = '_inlet1_paths'
_inlet2_paths = 'inlet2_paths' $ __inlet2_paths = '_inlet2_paths'
_dfl_labels   = 'dfl_labels'   $ __dfl_labels   = '_dfl_labels'

view2w
wincln,1
wincln,2
g_picres,GRAPH_picRes
boldfont,1

wintitle,1,'ACESSO 01','FLECHA','ELS-Freq [mm]',,1,13
wintitle,2,'ACESSO 02','FLECHA','ELS-Freq [mm]',,1,13

/gformat,f,2,2
/plopts,leg3,on
/eshape,1
/type,1,3
/udoc,1,cntr,bottom
/udoc,2,cntr,bottom

cmsel,s,COMPA_HDW_1
cmsel,a,COMPA_HDW_2
esla
nsle
cm,COMPE_bg,elem
/color,cm,dgra,COMPE_bg

/window,1,on
/window,2,off
cmsel,s,COMPA_HDW_1
esla
nsle
wpcsys,1,CS_revTunnel
/auto,1
eplot
/user,1

/window,1,off
/window,2,on
cmsel,s,COMPA_HDW_2
esla
nsle
wpcsys,2,CS_tunnel
/auto,2
eplot
/user,2

go2png,GRAPH_picRes
  /window,1,on
  /window,2,off
  cmsel,s,COMPA_HDW_1
  esla
  nsle
  eplot

  /noerase

  cleanplot,'mpathplot',baseScale,,'__inlet1_paths','__dfl_labels'

  /device,vector,on
  /color,cm,whit,COMPE_bg
  eplot
  /device,vector,off
  /color,cm,dgra,COMPE_bg

  esel,none
  wpcsys,1,CS_tunnel

  /window,1,off
  /window,2,on
  cmsel,s,COMPA_HDW_2
  esla
  nsle
  eplot

  cleanplot,'mpathplot',baseScale,,'__inlet2_paths','__dfl_labels'

  /device,vector,on
  /color,cm,whit,COMPE_bg
  eplot

endpng,'INLETS_deflection',,,,,FOLDER_results

/erase
/annot,dele
/type,all,3
/device,vector,off
/eshape,0
view1w
windefa,1

! Approach slab deflections
*del , appslab_paths ,      , nopr
*del , dfl_labels    ,      , nopr
*dim , appslab_paths , char , 4
*dim , dfl_labels    , char , 4

appslab_paths(1) = 'APPL'   , 'APPL'   , 'APPR'   , 'APPR'
dfl_labels(1)    = maxLabel , minLabel , maxLabel , minLabel

_appslab_paths = 'appslab_paths' $ __appslab_paths = '_appslab_paths'
_dfl_labels    = 'dfl_labels'    $ __dfl_labels    = '_dfl_labels'

view1w
wincln,1
g_picres,GRAPH_picRes
boldfont,1
wintitle,1,'LAJES DE APROX.','FLECHA','ELS-Freq. [mm]',,1,13

/gformat,f,2,2
/plopts,leg3,on
/eshape,1
/angle,1,0
/type,1,3
/udoc,1,cntr,bottom

cmsel,s,COMPA_tunnel
cmsel,a,COMPA_approach
esla
nsle
cm,COMPE_bg,elem
/color,cm,dgra,COMPE_bg
wpcsys,1,CS_tunnel
/auto,1
eplot
/user,1

go2png,GRAPH_picRes
  eplot
  /noerase

  cleanplot,'mpathplot',baseScale,,'__appslab_paths','__dfl_labels'

  /device,vector,on
  /type,1,3
  /color,cm,whit,COMPE_bg
  eplot

endpng,'APPSLAB_deflections',,,,,FOLDER_results

/erase
/annot,dele
/type,1,3
/device,vector,off
/eshape,0
view1w
windefa,1
