! TUNNEL_V2_YABOVE, parm,   NZ
! TUNNEL_V2_YABOVE, arg1, arg2


! Calculate embankment height above node
*if,GEO_EMB_slopeBeg,eq,90,then
  yBeg = yPT2
*else
  *afun,deg
  yBeg = yPT1+TAN(GEO_EMB_slopeBeg)*(arg2-zPT1)
  *afun,rad
*endif

*if,GEO_EMB_slopeEnd,eq,90,then
  yEnd = yPT2
*else
  *afun,deg
  yEnd = yPT4+TAN(GEO_EMB_slopeEnd)*(zPT4-arg2)
  *afun,rad
*endif

yPlateau = yPT2

%arg1% = (0>(yBeg<(yPlateau<yEnd)))
